@echo off
echo Starting Brainia Development Environment...
echo Opening Mobile View...
start "" "http://localhost:3000"
echo Opening Desktop View...
start "" "http://localhost:3000/?view=desktop"
echo Starting Next.js Server...
npm run dev
